/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Scorpion
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        painelFerramentas = new javax.swing.JPanel();
        ferramentas = new javax.swing.JToolBar();
        btnGauss = new javax.swing.JButton();
        btnJordan = new javax.swing.JButton();
        btnBissecao = new javax.swing.JButton();
        btnCordas = new javax.swing.JButton();
        barraDeMenu = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        subMenuSair = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Werton");

        desktop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1221, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );

        painelFerramentas.setBackground(new java.awt.Color(153, 153, 153));
        painelFerramentas.setForeground(new java.awt.Color(0, 255, 255));
        painelFerramentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ferramentas.setBackground(new java.awt.Color(255, 255, 255));
        ferramentas.setFloatable(false);
        ferramentas.setRollover(true);
        ferramentas.setAutoscrolls(true);

        btnGauss.setBackground(new java.awt.Color(255, 255, 255));
        btnGauss.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGauss.setForeground(new java.awt.Color(255, 255, 255));
        btnGauss.setText("Gauss");
        btnGauss.setFocusable(false);
        btnGauss.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGauss.setPreferredSize(new java.awt.Dimension(300, 80));
        btnGauss.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGaussActionPerformed(evt);
            }
        });
        ferramentas.add(btnGauss);

        btnJordan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnJordan.setForeground(new java.awt.Color(255, 255, 255));
        btnJordan.setText("Jordan");
        btnJordan.setFocusable(false);
        btnJordan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnJordan.setPreferredSize(new java.awt.Dimension(300, 80));
        btnJordan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnJordan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJordanActionPerformed(evt);
            }
        });
        ferramentas.add(btnJordan);

        btnBissecao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBissecao.setForeground(new java.awt.Color(255, 255, 255));
        btnBissecao.setText("Bissecção");
        btnBissecao.setFocusable(false);
        btnBissecao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBissecao.setPreferredSize(new java.awt.Dimension(300, 80));
        btnBissecao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBissecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBissecaoActionPerformed(evt);
            }
        });
        ferramentas.add(btnBissecao);

        btnCordas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCordas.setForeground(new java.awt.Color(255, 255, 255));
        btnCordas.setText("Secante");
        btnCordas.setFocusable(false);
        btnCordas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCordas.setPreferredSize(new java.awt.Dimension(300, 80));
        btnCordas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCordas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCordasActionPerformed(evt);
            }
        });
        ferramentas.add(btnCordas);

        javax.swing.GroupLayout painelFerramentasLayout = new javax.swing.GroupLayout(painelFerramentas);
        painelFerramentas.setLayout(painelFerramentasLayout);
        painelFerramentasLayout.setHorizontalGroup(
            painelFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ferramentas, javax.swing.GroupLayout.DEFAULT_SIZE, 1221, Short.MAX_VALUE)
        );
        painelFerramentasLayout.setVerticalGroup(
            painelFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ferramentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        menuInicio.setText("Inicio");
        menuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInicioActionPerformed(evt);
            }
        });

        subMenuSair.setText("Sair");
        subMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuSairActionPerformed(evt);
            }
        });
        menuInicio.add(subMenuSair);

        barraDeMenu.add(menuInicio);

        menuAjuda.setText("Ajuda");

        menuSobre.setText("Sobre");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(menuSobre);

        barraDeMenu.add(menuAjuda);

        setJMenuBar(barraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelFerramentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(painelFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 641, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void subMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuSairActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_subMenuSairActionPerformed

    private void btnGaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGaussActionPerformed
        TelaGauss gauss = new TelaGauss();
        gauss.setVisible(true);
        desktop.add(gauss);
    }//GEN-LAST:event_btnGaussActionPerformed

    private void menuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuInicioActionPerformed

    private void btnJordanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJordanActionPerformed
        TelaJordan jordan = new TelaJordan();
        jordan.setVisible(true);
        desktop.add(jordan);
    }//GEN-LAST:event_btnJordanActionPerformed

    private void btnBissecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBissecaoActionPerformed
        TelaBissecao b = new TelaBissecao();
        b.setVisible(true);
        desktop.add(b);
    }//GEN-LAST:event_btnBissecaoActionPerformed

    private void btnCordasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCordasActionPerformed
       TelaSecante secante = new TelaSecante();
        secante.setVisible(true);
        desktop.add(secante);
    }//GEN-LAST:event_btnCordasActionPerformed

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);
        desktop.add(sobre);
        
    }//GEN-LAST:event_menuSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JButton btnBissecao;
    private javax.swing.JButton btnCordas;
    private javax.swing.JButton btnGauss;
    private javax.swing.JButton btnJordan;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JToolBar ferramentas;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenuItem menuSobre;
    private javax.swing.JPanel painelFerramentas;
    private javax.swing.JMenuItem subMenuSair;
    // End of variables declaration//GEN-END:variables
}
